[package]
name = "preprocess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray-npy = "*"
ndarray = "*"
base64 = "*"
tokio = { version = "1", features = ["rt-multi-thread", "fs", "macros"] }
